dbUsername: b816da2c32ad51
dbPassword: a1bc6465
dbServerUrl: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/ad_6bc4d13c46fbd3f
dbDriverClass: com.mysql.cj.jdbc.Driver
dbServerDialect: org.hibernate.dialect.MySQL5Dialect