dbUsername: bda9339dc70914
dbPassword: 870c33ad
dbServerUrl: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/friendmanagementsystem
dbDriverClass: com.mysql.cj.jdbc.Driver
dbServerDialect: org.hibernate.dialect.MySQL5Dialect